### ISSUE TITLE
Not able to connect to my zaptec charger

### ISSUE THREAD

**Issue by Tedvard** [PatrickE94/com.zaptec#3]
Have tried several times to connect.
- Changed zaptec connection from 4g to my local wifi
- Moved the Homey Pro device outside close to the zaptec charger to ensure it was close
- restared homey to factory reset to start again
- downloaded the zaptec app - seems like I can connect with my credetials but then Homey reports "no unit found" (or similar text)

**Comment by PatrickE94** [comment]
If you're able to connect to the charger with your app it's not likely the chargers connectivity that's the issue. 

Is it a Zaptec Go charger?

If possible, can you try pairing the charger and then create a diagnostics report for the app afterwards?

You'll find it under More, Apps, Zaptec, then the settings icon.

**Comment by Tedvard** [comment]
Thanks for replying. It is not a zaptec go it is a zaptec PRO.I will try again when i am back home. Most likely tomorrow. Best regardsTomSendt fra min iPhone27. aug. 2023 kl. 09:42 skrev Patrick Wadström ***@***.***>:﻿
If you're able to connect to the charger with your app it's not likely the chargers connectivity that's the issue.
Is it a Zaptec Go charger?
If possible, can you try pairing the charger and then create a diagnostics report for the app afterwards?
You'll find it under More, Apps, Zaptec, then the settings icon.

**Comment by Tedvard** [comment]
I tried the pairing again. Attached is the log and a picture of the scree. 

Zaptec pro diagnostic:
1f3407e1-324d-4a11-a1e0-e7f0ab20c3c6

![IMG_2970 (002)](https://github.com/PatrickE94/com.zaptec/assets/142234892/efb7d3d7-71ec-4815-bedc-33ad8782dae7)
The text on the picture is in norwegain. Translated - "No new product found"

**Comment by PatrickE94** [comment]
Hi,

The app currently searches only for Go chargers. So that explains why you don't find the pro charger. 

Do you know the difference in features between the Go and the Pro? I don't have a pro version, so I would have to blindly integrate it. If it's the same as a Go then it should be fairly low effort.

Best regars

**Comment by Tedvard** [comment]
This should help you. There are info about Pro in the document. If it isn't enough let me know and I can contact zaptec support.
https://zaptec.com/downloads/ZapChargerPro_Integration.pdf

**Comment by PatrickE94** [comment]
Thank you for the guidance. I have used this document to implement the current app for Go chargers. My issue with implemented a Pro charger is that I have none to test against. I will thus have to make a assumptions which I cannot validate. You will need to assist me with this part.

I have pushed a simple first attempt based on the Go charger (assuming similarities in behaviour) to the beta channel. Install via this [link](https://homey.app/a/com.zaptec/test/).

I would mostly suspect issues around load balancing and maybe trigger cards. Do give it a try and bring me back any feedback. If you get errors, please do submit diagnostic reports! They are very helpful for me.

**Comment by Tedvard** [comment]
Tried to install it but it seems like it won't load.
"Zaptec vil straks installeres på Homey." (Zaptec will soon be installed on Homey"

The page seems stuck.

**Comment by Tedvard** [comment]
If you want we can agree a date and time and work on this "line"

**Comment by PatrickE94** [comment]
Truly sorry, this app is developed in my free time as a best effort. I'm not really scheduling time for it. Check the app version in the settings view, if you have 1.4.0 you're on testing!

**Comment by Tedvard** [comment]
Understand you are doing it on your spear time and I appreciate it:-)
Tried again and now the homey pro came up as an option. But still can't find the unit.

Diagnostic report fcdeb18b-1153-4d59-b6dd-ba3bfefc1296

**Comment by Tedvard** [comment]
Hei Patrick. have you given up? :-)

**Comment by PatrickE94** [comment]
Hi, no sorry, it just slipped my mind and life has been a bit busy :). I pushed a new Beta now. It should be much "kinder" trying to find devices. Please try it out and see if it can find your charger.

**Comment by Tedvard** [comment]
Good progress, found the unit and was able to connect. Thanks
